apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: zx7hc99yc-nodejs
  janus-idp.io/tekton: zx7hc99yc-nodejs
  backstage.io/kubernetes-id: zx7hc99yc-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: zx7hc99yc-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
